# Generated by Django 4.0.1 on 2022-01-20 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_cuenta', models.PositiveIntegerField(unique=True)),
                ('nombre_paciente', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('hora', models.TimeField()),
                ('lugar', models.CharField(max_length=50)),
            ],
        ),
    ]
