# Generated by Django 4.0.1 on 2022-01-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_cita_numero_de_cuenta_alter_cita_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('telefono', models.BigIntegerField()),
                ('email', models.EmailField(default=0, max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='primer_apellido',
            new_name='apellidos',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='segundo_apellido',
        ),
    ]
